name: thesis
channels:
  - defaults
dependencies:
  - pip
  - python=3.10
  - gymnasium
  - numpy
  - pandas
  - tqdm
  - ipykernel
  - conda-forge::stable-baselines3
  - opencv
  - tensorflow
  - sb3-contrib
  - shimmy
  - pysr
