name: thesis-1
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - gymnasium
  - numpy
  - pandas
  - tqdm
  - ipykernel
  - stable-baselines3
  - opencv
  - sb3-contrib
  - shimmy
  - pip:
      - tensorflow
      - pysr
